## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x=np.arange(15).reshape(3,5)
y=np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.83391347 0.9844442  0.49834003 0.10412064 0.57338835]
 [0.61441517 0.85164211 0.6952315  0.14813488 0.31690488]
 [0.58923221 0.81204415 0.97352614 0.26335863 0.38081692]]


#### 연산 함수
 - add, substract, multiply, divide

In [8]:
# 같은 크기여야 함
print(np.add(x, y), "\n")
print(np.subtract(x, y), "\n")
print(np.multiply(x,y), "\n")
print(np.divide(x,y), "\n")

print("----------------------------------------------")
print()

print(x+y, "\n")
print(x-y, "\n")
print(x*y, "\n")
print(x/y, "\n")

[[ 0.83391347  1.9844442   2.49834003  3.10412064  4.57338835]
 [ 5.61441517  6.85164211  7.6952315   8.14813488  9.31690488]
 [10.58923221 11.81204415 12.97352614 13.26335863 14.38081692]] 

[[-0.83391347  0.0155558   1.50165997  2.89587936  3.42661165]
 [ 4.38558483  5.14835789  6.3047685   7.85186512  8.68309512]
 [ 9.41076779 10.18795585 11.02647386 12.73664137 13.61918308]] 

[[ 0.          0.9844442   0.99668006  0.31236193  2.29355339]
 [ 3.07207587  5.10985267  4.86662053  1.18507901  2.85214389]
 [ 5.89232211  8.93248565 11.68231372  3.42366218  5.3314369 ]] 

[[ 0.          1.0158016   4.01332401 28.81273022  6.9760748 ]
 [ 8.13781986  7.04521291 10.06858859 54.00483794 28.39968917]
 [16.97123783 13.54606151 12.32632537 49.3623469  36.76307228]] 

----------------------------------------------

[[ 0.83391347  1.9844442   2.49834003  3.10412064  4.57338835]
 [ 5.61441517  6.85164211  7.6952315   8.14813488  9.31690488]
 [10.58923221 11.81204415 12.97352614 13.26335863 14.38081

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [9]:
print(y)

[[0.83391347 0.9844442  0.49834003 0.10412064 0.57338835]
 [0.61441517 0.85164211 0.6952315  0.14813488 0.31690488]
 [0.58923221 0.81204415 0.97352614 0.26335863 0.38081692]]


In [13]:
print(np.mean(y)) #y.mean()
print(np.max(y))
print(np.argmax(y))
print(np.var(y))
print(np.median(y))
print(np.std(y))

0.5759675523339
0.9844442036651245
1
0.07691222349524159
0.5892322114620501
0.277330531127104


#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [14]:
y

array([[0.83391347, 0.9844442 , 0.49834003, 0.10412064, 0.57338835],
       [0.61441517, 0.85164211, 0.6952315 , 0.14813488, 0.31690488],
       [0.58923221, 0.81204415, 0.97352614, 0.26335863, 0.38081692]])

In [16]:
print(np.sum(y))
print(np.cumsum(y))

8.6395132850085
[0.83391347 1.81835767 2.3166977  2.42081834 2.99420669 3.60862186
 4.46026397 5.15549548 5.30363035 5.62053523 6.20976744 7.02181159
 7.99533773 8.25869636 8.63951329]


In [24]:
print(sum(y))
print(np.sum(y, axis=0))
print(np.sum(y, axis=1))

[2.03756085 2.64813046 2.16709768 0.51561415 1.27111015]
[2.03756085 2.64813046 2.16709768 0.51561415 1.27111015]
[2.99420669 2.62632854 3.01897805]


#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [25]:
z=np.random.randn(10)
print(z)

[-0.55665731 -0.48827642  1.00696814 -0.33912687  0.18571736 -1.05576235
 -0.08537227  0.26599176 -1.33876329  0.30511302]


In [27]:
print(z>0)
print(np.any(z>0))

[False False  True False  True False False  True False  True]
True


In [29]:
print(np.all(z>0))
print(np.all(z!=0))

False
True


#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [30]:
z=np.random.randn(10)
print(z)

[-1.14476384 -0.92364354 -1.11268404 -2.61409911  1.96731788  0.67020367
  2.26137841 -0.01566042 -0.62278307 -0.38932329]


In [31]:
np.where(z>0, z, 0) # where(조건, 참일때, 거짓일때)

array([0.        , 0.        , 0.        , 0.        , 1.96731788,
       0.67020367, 2.26137841, 0.        , 0.        , 0.        ])