## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [3]:
x=np.arange(15).reshape(3, 5)
y=np.random.rand(15).reshape(3, 5)

print(x)
print(y)
print()

print(x+y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.75683292 0.88208587 0.19728912 0.53289312 0.03022383]
 [0.58240515 0.59209314 0.52988732 0.06563108 0.02537661]
 [0.55630382 0.6708375  0.33814131 0.52815986 0.15624976]]

[[ 0.75683292  1.88208587  2.19728912  3.53289312  4.03022383]
 [ 5.58240515  6.59209314  7.52988732  8.06563108  9.02537661]
 [10.55630382 11.6708375  12.33814131 13.52815986 14.15624976]]


* Scalar(상수)와의 연산

In [4]:
x+2

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [5]:
x*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [6]:
x**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]], dtype=int32)

In [7]:
x%2==0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [18]:
a=np.arange(12).reshape(4,3)
b=np.arange(100, 103)
c=np.arange(1000, 1004)
d=b.reshape(1, 3)
e=np.arange(6).reshape(2,3)

print(a, "\n")
print(b, "\n")
print(c, "\n")
print(d, "\n")
print(e)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[100 101 102] 

[1000 1001 1002 1003] 

[[100 101 102]] 

[[0 1 2]
 [3 4 5]]


In [9]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [12]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [15]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [19]:
a+e

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 