## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [4]:
x=np.random.rand(3,3) # 정방행렬만 가능
print(x)
print()

print(np.linalg.inv(x))
print()

print(x@np.linalg.inv(x))
print()

print(np.matmul(x, np.linalg.inv(x)))

[[0.47455133 0.84032257 0.55389795]
 [0.61269911 0.65788873 0.27398621]
 [0.02146674 0.36544178 0.01591022]]

[[-1.2735355   2.68527858 -1.90573149]
 [-0.05492194 -0.06164873  2.9736889 ]
 [ 2.97980905 -2.20708112 -2.87867195]]

[[1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.93889390e-18 0.00000000e+00 1.00000000e+00]]

[[1.00000000e+00 2.22044605e-16 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [6.93889390e-18 0.00000000e+00 1.00000000e+00]]


#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [7]:
A=np.array([[1, 1], [2, 4]])
B=np.array([25, 64])

x=np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True